-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.BikePark exposing (..)

import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.ScalarCodecs
import EnturApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet EnturApi.ScalarCodecs.Id EnturApi.Object.BikePark
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (EnturApi.ScalarCodecs.codecs |> EnturApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


name : SelectionSet String EnturApi.Object.BikePark
name =
    Object.selectionForField "String" "name" [] Decode.string


spacesAvailable : SelectionSet (Maybe Int) EnturApi.Object.BikePark
spacesAvailable =
    Object.selectionForField "(Maybe Int)" "spacesAvailable" [] (Decode.int |> Decode.nullable)


realtime : SelectionSet (Maybe Bool) EnturApi.Object.BikePark
realtime =
    Object.selectionForField "(Maybe Bool)" "realtime" [] (Decode.bool |> Decode.nullable)


longitude : SelectionSet (Maybe Float) EnturApi.Object.BikePark
longitude =
    Object.selectionForField "(Maybe Float)" "longitude" [] (Decode.float |> Decode.nullable)


latitude : SelectionSet (Maybe Float) EnturApi.Object.BikePark
latitude =
    Object.selectionForField "(Maybe Float)" "latitude" [] (Decode.float |> Decode.nullable)
