-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.BookingArrangement exposing (..)

import EnturApi.Enum.BookingAccess
import EnturApi.Enum.BookingMethod
import EnturApi.Enum.PurchaseMoment
import EnturApi.Enum.PurchaseWhen
import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.ScalarCodecs
import EnturApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Who has access to book service?
-}
bookingAccess : SelectionSet (Maybe EnturApi.Enum.BookingAccess.BookingAccess) EnturApi.Object.BookingArrangement
bookingAccess =
    Object.selectionForField "(Maybe Enum.BookingAccess.BookingAccess)" "bookingAccess" [] (EnturApi.Enum.BookingAccess.decoder |> Decode.nullable)


{-| How should service be booked?
-}
bookingMethods : SelectionSet (Maybe (List (Maybe EnturApi.Enum.BookingMethod.BookingMethod))) EnturApi.Object.BookingArrangement
bookingMethods =
    Object.selectionForField "(Maybe (List (Maybe Enum.BookingMethod.BookingMethod)))" "bookingMethods" [] (EnturApi.Enum.BookingMethod.decoder |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| When should service be booked?
-}
bookWhen : SelectionSet (Maybe EnturApi.Enum.PurchaseWhen.PurchaseWhen) EnturApi.Object.BookingArrangement
bookWhen =
    Object.selectionForField "(Maybe Enum.PurchaseWhen.PurchaseWhen)" "bookWhen" [] (EnturApi.Enum.PurchaseWhen.decoder |> Decode.nullable)


{-| Latest time service can be booked. ISO 8601 timestamp
-}
latestBookingTime : SelectionSet (Maybe EnturApi.ScalarCodecs.LocalTime) EnturApi.Object.BookingArrangement
latestBookingTime =
    Object.selectionForField "(Maybe ScalarCodecs.LocalTime)" "latestBookingTime" [] (EnturApi.ScalarCodecs.codecs |> EnturApi.Scalar.unwrapCodecs |> .codecLocalTime |> .decoder |> Decode.nullable)


{-| Minimum period in advance service can be booked as a ISO 8601 duration
-}
minimumBookingPeriod : SelectionSet (Maybe String) EnturApi.Object.BookingArrangement
minimumBookingPeriod =
    Object.selectionForField "(Maybe String)" "minimumBookingPeriod" [] (Decode.string |> Decode.nullable)


{-| Textual description of booking arrangement for service
-}
bookingNote : SelectionSet (Maybe String) EnturApi.Object.BookingArrangement
bookingNote =
    Object.selectionForField "(Maybe String)" "bookingNote" [] (Decode.string |> Decode.nullable)


{-| When should ticket be purchased?
-}
buyWhen : SelectionSet (Maybe (List (Maybe EnturApi.Enum.PurchaseMoment.PurchaseMoment))) EnturApi.Object.BookingArrangement
buyWhen =
    Object.selectionForField "(Maybe (List (Maybe Enum.PurchaseMoment.PurchaseMoment)))" "buyWhen" [] (EnturApi.Enum.PurchaseMoment.decoder |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| Who should ticket be contacted for booking
-}
bookingContact : SelectionSet decodesTo EnturApi.Object.Contact -> SelectionSet (Maybe decodesTo) EnturApi.Object.BookingArrangement
bookingContact object_ =
    Object.selectionForCompositeField "bookingContact" [] object_ (identity >> Decode.nullable)
