-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.CarPark exposing (..)

import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.ScalarCodecs
import EnturApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet EnturApi.ScalarCodecs.Id EnturApi.Object.CarPark
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (EnturApi.ScalarCodecs.codecs |> EnturApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


name : SelectionSet String EnturApi.Object.CarPark
name =
    Object.selectionForField "String" "name" [] Decode.string


capacity : SelectionSet (Maybe Int) EnturApi.Object.CarPark
capacity =
    Object.selectionForField "(Maybe Int)" "capacity" [] (Decode.int |> Decode.nullable)


spacesAvailable : SelectionSet (Maybe Int) EnturApi.Object.CarPark
spacesAvailable =
    Object.selectionForField "(Maybe Int)" "spacesAvailable" [] (Decode.int |> Decode.nullable)


capacityHandicap : SelectionSet (Maybe Int) EnturApi.Object.CarPark
capacityHandicap =
    Object.selectionForField "(Maybe Int)" "capacityHandicap" [] (Decode.int |> Decode.nullable)


spacesAvailableHandicap : SelectionSet (Maybe Int) EnturApi.Object.CarPark
spacesAvailableHandicap =
    Object.selectionForField "(Maybe Int)" "spacesAvailableHandicap" [] (Decode.int |> Decode.nullable)


capacityRecharging : SelectionSet (Maybe Int) EnturApi.Object.CarPark
capacityRecharging =
    Object.selectionForField "(Maybe Int)" "capacityRecharging" [] (Decode.int |> Decode.nullable)


spacesAvailableRecharging : SelectionSet (Maybe Int) EnturApi.Object.CarPark
spacesAvailableRecharging =
    Object.selectionForField "(Maybe Int)" "spacesAvailableRecharging" [] (Decode.int |> Decode.nullable)


realtimeOccupancyAvailable : SelectionSet (Maybe Bool) EnturApi.Object.CarPark
realtimeOccupancyAvailable =
    Object.selectionForField "(Maybe Bool)" "realtimeOccupancyAvailable" [] (Decode.bool |> Decode.nullable)


longitude : SelectionSet (Maybe Float) EnturApi.Object.CarPark
longitude =
    Object.selectionForField "(Maybe Float)" "longitude" [] (Decode.float |> Decode.nullable)


latitude : SelectionSet (Maybe Float) EnturApi.Object.CarPark
latitude =
    Object.selectionForField "(Maybe Float)" "latitude" [] (Decode.float |> Decode.nullable)
