-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.Contact exposing (contactPerson, email, furtherDetails, phone, url)

import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.ScalarCodecs
import EnturApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Name of person to contact
-}
contactPerson : SelectionSet (Maybe String) EnturApi.Object.Contact
contactPerson =
    Object.selectionForField "(Maybe String)" "contactPerson" [] (Decode.string |> Decode.nullable)


{-| Email adress for contact
-}
email : SelectionSet (Maybe String) EnturApi.Object.Contact
email =
    Object.selectionForField "(Maybe String)" "email" [] (Decode.string |> Decode.nullable)


{-| Url for contact
-}
url : SelectionSet (Maybe String) EnturApi.Object.Contact
url =
    Object.selectionForField "(Maybe String)" "url" [] (Decode.string |> Decode.nullable)


{-| Phone number for contact
-}
phone : SelectionSet (Maybe String) EnturApi.Object.Contact
phone =
    Object.selectionForField "(Maybe String)" "phone" [] (Decode.string |> Decode.nullable)


{-| Textual description of how to get in contact
-}
furtherDetails : SelectionSet (Maybe String) EnturApi.Object.Contact
furtherDetails =
    Object.selectionForField "(Maybe String)" "furtherDetails" [] (Decode.string |> Decode.nullable)
