-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.InfoLink exposing (label, uri)

import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.ScalarCodecs
import EnturApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| URI
-}
uri : SelectionSet (Maybe String) EnturApi.Object.InfoLink
uri =
    Object.selectionForField "(Maybe String)" "uri" [] (Decode.string |> Decode.nullable)


{-| Label
-}
label : SelectionSet (Maybe String) EnturApi.Object.InfoLink
label =
    Object.selectionForField "(Maybe String)" "label" [] (Decode.string |> Decode.nullable)
