-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.Interchange exposing (..)

import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.ScalarCodecs
import EnturApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The Line/Route/ServiceJourney changes, but the passenger can stay seated.
-}
staySeated : SelectionSet (Maybe Bool) EnturApi.Object.Interchange
staySeated =
    Object.selectionForField "(Maybe Bool)" "staySeated" [] (Decode.bool |> Decode.nullable)


{-| The interchange is guaranteed by the operator(s). Usually up to a maximum wait time.
-}
guaranteed : SelectionSet (Maybe Bool) EnturApi.Object.Interchange
guaranteed =
    Object.selectionForField "(Maybe Bool)" "guaranteed" [] (Decode.bool |> Decode.nullable)


fromLine : SelectionSet decodesTo EnturApi.Object.Line -> SelectionSet (Maybe decodesTo) EnturApi.Object.Interchange
fromLine object_ =
    Object.selectionForCompositeField "FromLine" [] object_ (identity >> Decode.nullable)


toLine : SelectionSet decodesTo EnturApi.Object.Line -> SelectionSet (Maybe decodesTo) EnturApi.Object.Interchange
toLine object_ =
    Object.selectionForCompositeField "ToLine" [] object_ (identity >> Decode.nullable)


fromServiceJourney : SelectionSet decodesTo EnturApi.Object.ServiceJourney -> SelectionSet (Maybe decodesTo) EnturApi.Object.Interchange
fromServiceJourney object_ =
    Object.selectionForCompositeField "FromServiceJourney" [] object_ (identity >> Decode.nullable)


toServiceJourney : SelectionSet decodesTo EnturApi.Object.ServiceJourney -> SelectionSet (Maybe decodesTo) EnturApi.Object.Interchange
toServiceJourney object_ =
    Object.selectionForCompositeField "ToServiceJourney" [] object_ (identity >> Decode.nullable)
