-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.JourneyPattern exposing (..)

import EnturApi.Enum.DirectionType
import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.ScalarCodecs
import EnturApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet EnturApi.ScalarCodecs.Id EnturApi.Object.JourneyPattern
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (EnturApi.ScalarCodecs.codecs |> EnturApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


line : SelectionSet decodesTo EnturApi.Object.Line -> SelectionSet decodesTo EnturApi.Object.JourneyPattern
line object_ =
    Object.selectionForCompositeField "line" [] object_ identity


directionType : SelectionSet (Maybe EnturApi.Enum.DirectionType.DirectionType) EnturApi.Object.JourneyPattern
directionType =
    Object.selectionForField "(Maybe Enum.DirectionType.DirectionType)" "directionType" [] (EnturApi.Enum.DirectionType.decoder |> Decode.nullable)


name : SelectionSet (Maybe String) EnturApi.Object.JourneyPattern
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


destinationDisplay : SelectionSet decodesTo EnturApi.Object.DestinationDisplay -> SelectionSet (Maybe decodesTo) EnturApi.Object.JourneyPattern
destinationDisplay object_ =
    Object.selectionForCompositeField "destinationDisplay" [] object_ (identity >> Decode.nullable)


serviceJourneys : SelectionSet decodesTo EnturApi.Object.ServiceJourney -> SelectionSet (List decodesTo) EnturApi.Object.JourneyPattern
serviceJourneys object_ =
    Object.selectionForCompositeField "serviceJourneys" [] object_ (identity >> Decode.list)


type alias ServiceJourneysForDateOptionalArguments =
    { date : OptionalArgument EnturApi.ScalarCodecs.Date }


{-| List of service journeys for the journey pattern for a given date
-}
serviceJourneysForDate : (ServiceJourneysForDateOptionalArguments -> ServiceJourneysForDateOptionalArguments) -> SelectionSet decodesTo EnturApi.Object.ServiceJourney -> SelectionSet (List decodesTo) EnturApi.Object.JourneyPattern
serviceJourneysForDate fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { date = Absent }

        optionalArgs =
            [ Argument.optional "date" filledInOptionals.date (EnturApi.ScalarCodecs.codecs |> EnturApi.Scalar.unwrapEncoder .codecDate) ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "serviceJourneysForDate" optionalArgs object_ (identity >> Decode.list)


{-| Quays visited by service journeys for this journey patterns
-}
quays : SelectionSet decodesTo EnturApi.Object.Quay -> SelectionSet (List decodesTo) EnturApi.Object.JourneyPattern
quays object_ =
    Object.selectionForCompositeField "quays" [] object_ (identity >> Decode.list)


pointsOnLink : SelectionSet decodesTo EnturApi.Object.PointsOnLink -> SelectionSet (Maybe decodesTo) EnturApi.Object.JourneyPattern
pointsOnLink object_ =
    Object.selectionForCompositeField "pointsOnLink" [] object_ (identity >> Decode.nullable)


{-| Get all situations active for the journey pattern
-}
situations : SelectionSet decodesTo EnturApi.Object.PtSituationElement -> SelectionSet (List (Maybe decodesTo)) EnturApi.Object.JourneyPattern
situations object_ =
    Object.selectionForCompositeField "situations" [] object_ (identity >> Decode.nullable >> Decode.list)


notices : SelectionSet decodesTo EnturApi.Object.Notice -> SelectionSet (List (Maybe decodesTo)) EnturApi.Object.JourneyPattern
notices object_ =
    Object.selectionForCompositeField "notices" [] object_ (identity >> Decode.nullable >> Decode.list)
