-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.KeyValue exposing (key, typeOfKey, value)

import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.ScalarCodecs
import EnturApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Identifier of value.
-}
key : SelectionSet (Maybe String) EnturApi.Object.KeyValue
key =
    Object.selectionForField "(Maybe String)" "key" [] (Decode.string |> Decode.nullable)


{-| The actual value
-}
value : SelectionSet (Maybe String) EnturApi.Object.KeyValue
value =
    Object.selectionForField "(Maybe String)" "value" [] (Decode.string |> Decode.nullable)


{-| Identifier of type of key
-}
typeOfKey : SelectionSet (Maybe String) EnturApi.Object.KeyValue
typeOfKey =
    Object.selectionForField "(Maybe String)" "typeOfKey" [] (Decode.string |> Decode.nullable)
