-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.MultilingualString exposing (..)

import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.ScalarCodecs
import EnturApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


value : SelectionSet (Maybe String) EnturApi.Object.MultilingualString
value =
    Object.selectionForField "(Maybe String)" "value" [] (Decode.string |> Decode.nullable)


language : SelectionSet (Maybe String) EnturApi.Object.MultilingualString
language =
    Object.selectionForField "(Maybe String)" "language" [] (Decode.string |> Decode.nullable)
