-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.Notice exposing (..)

import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.ScalarCodecs
import EnturApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet (Maybe String) EnturApi.Object.Notice
id =
    Object.selectionForField "(Maybe String)" "id" [] (Decode.string |> Decode.nullable)


text : SelectionSet (Maybe String) EnturApi.Object.Notice
text =
    Object.selectionForField "(Maybe String)" "text" [] (Decode.string |> Decode.nullable)


publicCode : SelectionSet (Maybe String) EnturApi.Object.Notice
publicCode =
    Object.selectionForField "(Maybe String)" "publicCode" [] (Decode.string |> Decode.nullable)
