-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.Operator exposing (..)

import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.ScalarCodecs
import EnturApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Operator id
-}
id : SelectionSet EnturApi.ScalarCodecs.Id EnturApi.Object.Operator
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (EnturApi.ScalarCodecs.codecs |> EnturApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


name : SelectionSet String EnturApi.Object.Operator
name =
    Object.selectionForField "String" "name" [] Decode.string


url : SelectionSet (Maybe String) EnturApi.Object.Operator
url =
    Object.selectionForField "(Maybe String)" "url" [] (Decode.string |> Decode.nullable)


phone : SelectionSet (Maybe String) EnturApi.Object.Operator
phone =
    Object.selectionForField "(Maybe String)" "phone" [] (Decode.string |> Decode.nullable)


{-| Branding for operator.
-}
branding : SelectionSet decodesTo EnturApi.Object.Branding -> SelectionSet (Maybe decodesTo) EnturApi.Object.Operator
branding object_ =
    Object.selectionForCompositeField "branding" [] object_ (identity >> Decode.nullable)


lines : SelectionSet decodesTo EnturApi.Object.Line -> SelectionSet (List (Maybe decodesTo)) EnturApi.Object.Operator
lines object_ =
    Object.selectionForCompositeField "lines" [] object_ (identity >> Decode.nullable >> Decode.list)


serviceJourney : SelectionSet decodesTo EnturApi.Object.ServiceJourney -> SelectionSet (List (Maybe decodesTo)) EnturApi.Object.Operator
serviceJourney object_ =
    Object.selectionForCompositeField "serviceJourney" [] object_ (identity >> Decode.nullable >> Decode.list)
