-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.Organisation exposing (..)

import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.ScalarCodecs
import EnturApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Organisation id
-}
id : SelectionSet EnturApi.ScalarCodecs.Id EnturApi.Object.Organisation
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (EnturApi.ScalarCodecs.codecs |> EnturApi.Scalar.unwrapCodecs |> .codecId |> .decoder)


name : SelectionSet String EnturApi.Object.Organisation
name =
    Object.selectionForField "String" "name" [] Decode.string


url : SelectionSet (Maybe String) EnturApi.Object.Organisation
url =
    Object.selectionForField "(Maybe String)" "url" [] (Decode.string |> Decode.nullable)


timezone : SelectionSet String EnturApi.Object.Organisation
timezone =
    Object.selectionForField "String" "timezone" [] Decode.string


lang : SelectionSet (Maybe String) EnturApi.Object.Organisation
lang =
    Object.selectionForField "(Maybe String)" "lang" [] (Decode.string |> Decode.nullable)


phone : SelectionSet (Maybe String) EnturApi.Object.Organisation
phone =
    Object.selectionForField "(Maybe String)" "phone" [] (Decode.string |> Decode.nullable)


fareUrl : SelectionSet (Maybe String) EnturApi.Object.Organisation
fareUrl =
    Object.selectionForField "(Maybe String)" "fareUrl" [] (Decode.string |> Decode.nullable)


lines : SelectionSet decodesTo EnturApi.Object.Line -> SelectionSet (List (Maybe decodesTo)) EnturApi.Object.Organisation
lines object_ =
    Object.selectionForCompositeField "lines" [] object_ (identity >> Decode.nullable >> Decode.list)


{-| Get all situations active for the organisation
-}
situations : SelectionSet decodesTo EnturApi.Object.PtSituationElement -> SelectionSet (List (Maybe decodesTo)) EnturApi.Object.Organisation
situations object_ =
    Object.selectionForCompositeField "situations" [] object_ (identity >> Decode.nullable >> Decode.list)
