-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.Place exposing (bikePark, bikeRentalStation, carPark, latitude, longitude, name, quay, vertexType)

import EnturApi.Enum.VertexType
import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.ScalarCodecs
import EnturApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| For transit quays, the name of the quay. For points of interest, the name of the POI.
-}
name : SelectionSet (Maybe String) EnturApi.Object.Place
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| Type of vertex. (Normal, Bike sharing station, Bike P+R, Transit quay) Mostly used for better localization of bike sharing and P+R station names
-}
vertexType : SelectionSet (Maybe EnturApi.Enum.VertexType.VertexType) EnturApi.Object.Place
vertexType =
    Object.selectionForField "(Maybe Enum.VertexType.VertexType)" "vertexType" [] (EnturApi.Enum.VertexType.decoder |> Decode.nullable)


{-| The latitude of the place.
-}
latitude : SelectionSet Float EnturApi.Object.Place
latitude =
    Object.selectionForField "Float" "latitude" [] Decode.float


{-| The longitude of the place.
-}
longitude : SelectionSet Float EnturApi.Object.Place
longitude =
    Object.selectionForField "Float" "longitude" [] Decode.float


{-| The quay related to the place.
-}
quay : SelectionSet decodesTo EnturApi.Object.Quay -> SelectionSet (Maybe decodesTo) EnturApi.Object.Place
quay object_ =
    Object.selectionForCompositeField "quay" [] object_ (identity >> Decode.nullable)


{-| The bike rental station related to the place
-}
bikeRentalStation : SelectionSet decodesTo EnturApi.Object.BikeRentalStation -> SelectionSet (Maybe decodesTo) EnturApi.Object.Place
bikeRentalStation object_ =
    Object.selectionForCompositeField "bikeRentalStation" [] object_ (identity >> Decode.nullable)


{-| The bike parking related to the place
-}
bikePark : SelectionSet decodesTo EnturApi.Object.BikePark -> SelectionSet (Maybe decodesTo) EnturApi.Object.Place
bikePark object_ =
    Object.selectionForCompositeField "bikePark" [] object_ (identity >> Decode.nullable)


{-| The car parking related to the place
-}
carPark : SelectionSet decodesTo EnturApi.Object.CarPark -> SelectionSet (Maybe decodesTo) EnturApi.Object.Place
carPark object_ =
    Object.selectionForCompositeField "carPark" [] object_ (identity >> Decode.nullable)
