-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.PointsOnLink exposing (length, points)

import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.ScalarCodecs
import EnturApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| The number of points in the string
-}
length : SelectionSet (Maybe Int) EnturApi.Object.PointsOnLink
length =
    Object.selectionForField "(Maybe Int)" "length" [] (Decode.int |> Decode.nullable)


{-| The encoded points of the polyline. Be aware that the string could contain escape characters that need to be accounted for. (<https://www.freeformatter.com/javascript-escape.html>)
-}
points : SelectionSet (Maybe String) EnturApi.Object.PointsOnLink
points =
    Object.selectionForField "(Maybe String)" "points" [] (Decode.string |> Decode.nullable)
