-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.Presentation exposing (colour, textColour)

import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.ScalarCodecs
import EnturApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


colour : SelectionSet (Maybe String) EnturApi.Object.Presentation
colour =
    Object.selectionForField "(Maybe String)" "colour" [] (Decode.string |> Decode.nullable)


textColour : SelectionSet (Maybe String) EnturApi.Object.Presentation
textColour =
    Object.selectionForField "(Maybe String)" "textColour" [] (Decode.string |> Decode.nullable)
