-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.RoutingParameters exposing (alightSlack, allowBikeRental, bikeBoardCost, bikeParkAndRide, bikeParkCost, bikeParkTime, bikeRentalDropOffCost, bikeRentalDropOffTime, bikeRentalPickupCost, bikeRentalPickupTime, bikeSpeed, boardSlack, carAccelerationSpeed, carDecelerationSpeed, carDropOffTime, carSpeed, compactLegsByReversedSearch, disableAlertFiltering, disableRemainingWeightHeuristic, elevatorBoardCost, elevatorBoardTime, elevatorHopCost, elevatorHopTime, geoIdElevation, ignoreRealTimeUpdates, includedPlannedCancellations, interchangeAllowedPenalty, kissAndRide, maxPreTransitTime, maxSlope, maxTransferWalkDistance, maxTransfers, maxWalkDistance, noInterchangePenalty, numItineraries, onlyTransitTrips, otherThanPreferredRoutesPenalty, parkAndRide, preTransitOverageRate, preTransitPenalty, preTransitReluctance, preferredInterchangePenalty, recommendedInterchangePenalty, reverseOptimizeOnTheFly, rideAndKiss, showIntermediateStops, softPreTransitLimiting, softWalkLimiting, softWalkOverageRate, softWalkPenalty, stairsReluctance, transferPenalty, transferSlack, turnReluctance, useTraffic, waitAtBeginningFactor, waitReluctance, walkBoardCost, walkOnStreetReluctance, walkReluctance, walkSpeed, wheelChairAccessible)

import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.ScalarCodecs
import EnturApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Max walk speed along streets, in meters per second
-}
walkSpeed : SelectionSet (Maybe Float) EnturApi.Object.RoutingParameters
walkSpeed =
    Object.selectionForField "(Maybe Float)" "walkSpeed" [] (Decode.float |> Decode.nullable)


{-| Max bike speed along streets, in meters per second
-}
bikeSpeed : SelectionSet (Maybe Float) EnturApi.Object.RoutingParameters
bikeSpeed =
    Object.selectionForField "(Maybe Float)" "bikeSpeed" [] (Decode.float |> Decode.nullable)


{-| Max car speed along streets, in meters per second
-}
carSpeed : SelectionSet (Maybe Float) EnturApi.Object.RoutingParameters
carSpeed =
    Object.selectionForField "(Maybe Float)" "carSpeed" [] (Decode.float |> Decode.nullable)


{-| The maximum distance (in meters) the user is willing to walk for access/egress legs.
-}
maxWalkDistance : SelectionSet (Maybe Float) EnturApi.Object.RoutingParameters
maxWalkDistance =
    Object.selectionForField "(Maybe Float)" "maxWalkDistance" [] (Decode.float |> Decode.nullable)


{-| The maximum distance (in meters) the user is willing to walk for transfer legs.
-}
maxTransferWalkDistance : SelectionSet (Maybe Float) EnturApi.Object.RoutingParameters
maxTransferWalkDistance =
    Object.selectionForField "(Maybe Float)" "maxTransferWalkDistance" [] (Decode.float |> Decode.nullable)


{-| The maximum time (in seconds) of pre-transit travel when using drive-to-transit (park and ride or kiss and ride).
-}
maxPreTransitTime : SelectionSet (Maybe Float) EnturApi.Object.RoutingParameters
maxPreTransitTime =
    Object.selectionForField "(Maybe Float)" "maxPreTransitTime" [] (Decode.float |> Decode.nullable)


{-| Whether the trip must be wheelchair accessible.
-}
wheelChairAccessible : SelectionSet (Maybe Bool) EnturApi.Object.RoutingParameters
wheelChairAccessible =
    Object.selectionForField "(Maybe Bool)" "wheelChairAccessible" [] (Decode.bool |> Decode.nullable)


{-| The maximum number of itineraries to return.
-}
numItineraries : SelectionSet (Maybe Int) EnturApi.Object.RoutingParameters
numItineraries =
    Object.selectionForField "(Maybe Int)" "numItineraries" [] (Decode.int |> Decode.nullable)


{-| The maximum slope of streets for wheelchair trips.
-}
maxSlope : SelectionSet (Maybe Float) EnturApi.Object.RoutingParameters
maxSlope =
    Object.selectionForField "(Maybe Float)" "maxSlope" [] (Decode.float |> Decode.nullable)


{-| Whether the planner should return intermediate stops lists for transit legs.
-}
showIntermediateStops : SelectionSet (Maybe Bool) EnturApi.Object.RoutingParameters
showIntermediateStops =
    Object.selectionForField "(Maybe Bool)" "showIntermediateStops" [] (Decode.bool |> Decode.nullable)


{-| An extra penalty added on transfers (i.e. all boardings except the first one).
-}
transferPenalty : SelectionSet (Maybe Int) EnturApi.Object.RoutingParameters
transferPenalty =
    Object.selectionForField "(Maybe Int)" "transferPenalty" [] (Decode.int |> Decode.nullable)


{-| A multiplier for how bad walking is, compared to being in transit for equal lengths of time.
-}
walkReluctance : SelectionSet (Maybe Float) EnturApi.Object.RoutingParameters
walkReluctance =
    Object.selectionForField "(Maybe Float)" "walkReluctance" [] (Decode.float |> Decode.nullable)


{-| Used instead of walkReluctance for stairs.
-}
stairsReluctance : SelectionSet (Maybe Float) EnturApi.Object.RoutingParameters
stairsReluctance =
    Object.selectionForField "(Maybe Float)" "stairsReluctance" [] (Decode.float |> Decode.nullable)


{-| Multiplicative factor on expected turning time.
-}
turnReluctance : SelectionSet (Maybe Float) EnturApi.Object.RoutingParameters
turnReluctance =
    Object.selectionForField "(Maybe Float)" "turnReluctance" [] (Decode.float |> Decode.nullable)


{-| How much more reluctant is the user to walk on streets with car traffic allowed.
-}
walkOnStreetReluctance : SelectionSet (Maybe Float) EnturApi.Object.RoutingParameters
walkOnStreetReluctance =
    Object.selectionForField "(Maybe Float)" "walkOnStreetReluctance" [] (Decode.float |> Decode.nullable)


{-| How long does it take to get on an elevator, on average.
-}
elevatorBoardTime : SelectionSet (Maybe Int) EnturApi.Object.RoutingParameters
elevatorBoardTime =
    Object.selectionForField "(Maybe Int)" "elevatorBoardTime" [] (Decode.int |> Decode.nullable)


{-| What is the cost of boarding a elevator?
-}
elevatorBoardCost : SelectionSet (Maybe Int) EnturApi.Object.RoutingParameters
elevatorBoardCost =
    Object.selectionForField "(Maybe Int)" "elevatorBoardCost" [] (Decode.int |> Decode.nullable)


{-| How long does it take to advance one floor on an elevator?
-}
elevatorHopTime : SelectionSet (Maybe Int) EnturApi.Object.RoutingParameters
elevatorHopTime =
    Object.selectionForField "(Maybe Int)" "elevatorHopTime" [] (Decode.int |> Decode.nullable)


{-| What is the cost of travelling one floor on an elevator?
-}
elevatorHopCost : SelectionSet (Maybe Int) EnturApi.Object.RoutingParameters
elevatorHopCost =
    Object.selectionForField "(Maybe Int)" "elevatorHopCost" [] (Decode.int |> Decode.nullable)


{-| Time to rent a bike.
-}
bikeRentalPickupTime : SelectionSet (Maybe Int) EnturApi.Object.RoutingParameters
bikeRentalPickupTime =
    Object.selectionForField "(Maybe Int)" "bikeRentalPickupTime" [] (Decode.int |> Decode.nullable)


{-| Cost to rent a bike.
-}
bikeRentalPickupCost : SelectionSet (Maybe Int) EnturApi.Object.RoutingParameters
bikeRentalPickupCost =
    Object.selectionForField "(Maybe Int)" "bikeRentalPickupCost" [] (Decode.int |> Decode.nullable)


{-| Time to drop-off a rented bike.
-}
bikeRentalDropOffTime : SelectionSet (Maybe Int) EnturApi.Object.RoutingParameters
bikeRentalDropOffTime =
    Object.selectionForField "(Maybe Int)" "bikeRentalDropOffTime" [] (Decode.int |> Decode.nullable)


{-| Cost to drop-off a rented bike.
-}
bikeRentalDropOffCost : SelectionSet (Maybe Int) EnturApi.Object.RoutingParameters
bikeRentalDropOffCost =
    Object.selectionForField "(Maybe Int)" "bikeRentalDropOffCost" [] (Decode.int |> Decode.nullable)


{-| Time to park a bike.
-}
bikeParkTime : SelectionSet (Maybe Int) EnturApi.Object.RoutingParameters
bikeParkTime =
    Object.selectionForField "(Maybe Int)" "bikeParkTime" [] (Decode.int |> Decode.nullable)


{-| Cost to park a bike.
-}
bikeParkCost : SelectionSet (Maybe Int) EnturApi.Object.RoutingParameters
bikeParkCost =
    Object.selectionForField "(Maybe Int)" "bikeParkCost" [] (Decode.int |> Decode.nullable)


{-| Time to park a car in a park and ride, w/o taking into account driving and walking cost.
-}
carDropOffTime : SelectionSet (Maybe Int) EnturApi.Object.RoutingParameters
carDropOffTime =
    Object.selectionForField "(Maybe Int)" "carDropOffTime" [] (Decode.int |> Decode.nullable)


{-| How much worse is waiting for a transit vehicle than being on a transit vehicle, as a multiplier.
-}
waitReluctance : SelectionSet (Maybe Float) EnturApi.Object.RoutingParameters
waitReluctance =
    Object.selectionForField "(Maybe Float)" "waitReluctance" [] (Decode.float |> Decode.nullable)


{-| How much less bad is waiting at the beginning of the trip (replaces waitReluctance on the first boarding).
-}
waitAtBeginningFactor : SelectionSet (Maybe Float) EnturApi.Object.RoutingParameters
waitAtBeginningFactor =
    Object.selectionForField "(Maybe Float)" "waitAtBeginningFactor" [] (Decode.float |> Decode.nullable)


{-| This prevents unnecessary transfers by adding a cost for boarding a vehicle.
-}
walkBoardCost : SelectionSet (Maybe Int) EnturApi.Object.RoutingParameters
walkBoardCost =
    Object.selectionForField "(Maybe Int)" "walkBoardCost" [] (Decode.int |> Decode.nullable)


{-| Separate cost for boarding a vehicle with a bicycle, which is more difficult than on foot.
-}
bikeBoardCost : SelectionSet (Maybe Int) EnturApi.Object.RoutingParameters
bikeBoardCost =
    Object.selectionForField "(Maybe Int)" "bikeBoardCost" [] (Decode.int |> Decode.nullable)


{-| Penalty added for using every route that is not preferred if user set any route as preferred. We return number of seconds that we are willing to wait for preferred route.
-}
otherThanPreferredRoutesPenalty : SelectionSet (Maybe Int) EnturApi.Object.RoutingParameters
otherThanPreferredRoutesPenalty =
    Object.selectionForField "(Maybe Int)" "otherThanPreferredRoutesPenalty" [] (Decode.int |> Decode.nullable)


{-| A global minimum transfer time (in seconds) that specifies the minimum amount of time that must pass between exiting one transit vehicle and boarding another.
-}
transferSlack : SelectionSet (Maybe Int) EnturApi.Object.RoutingParameters
transferSlack =
    Object.selectionForField "(Maybe Int)" "transferSlack" [] (Decode.int |> Decode.nullable)


{-| Invariant: boardSlack + alightSlack <= transferSlack.
-}
boardSlack : SelectionSet (Maybe Int) EnturApi.Object.RoutingParameters
boardSlack =
    Object.selectionForField "(Maybe Int)" "boardSlack" [] (Decode.int |> Decode.nullable)


{-| Invariant: boardSlack + alightSlack <= transferSlack.
-}
alightSlack : SelectionSet (Maybe Int) EnturApi.Object.RoutingParameters
alightSlack =
    Object.selectionForField "(Maybe Int)" "alightSlack" [] (Decode.int |> Decode.nullable)


{-| Maximum number of transfers returned in a trip plan.
-}
maxTransfers : SelectionSet (Maybe Int) EnturApi.Object.RoutingParameters
maxTransfers =
    Object.selectionForField "(Maybe Int)" "maxTransfers" [] (Decode.int |> Decode.nullable)


{-| When true, reverse optimize this search on the fly whenever needed, rather than reverse-optimizing the entire path when it's done.
-}
reverseOptimizeOnTheFly : SelectionSet (Maybe Bool) EnturApi.Object.RoutingParameters
reverseOptimizeOnTheFly =
    Object.selectionForField "(Maybe Bool)" "reverseOptimizeOnTheFly" [] (Decode.bool |> Decode.nullable)


{-| When true, do a full reversed search to compact the legs of the GraphPath.
-}
compactLegsByReversedSearch : SelectionSet (Maybe Bool) EnturApi.Object.RoutingParameters
compactLegsByReversedSearch =
    Object.selectionForField "(Maybe Bool)" "compactLegsByReversedSearch" [] (Decode.bool |> Decode.nullable)


{-| The deceleration speed of an automobile, in meters per second per second.
-}
carDecelerationSpeed : SelectionSet (Maybe Float) EnturApi.Object.RoutingParameters
carDecelerationSpeed =
    Object.selectionForField "(Maybe Float)" "carDecelerationSpeed" [] (Decode.float |> Decode.nullable)


{-| The acceleration speed of an automobile, in meters per second per second.
-}
carAccelerationSpeed : SelectionSet (Maybe Float) EnturApi.Object.RoutingParameters
carAccelerationSpeed =
    Object.selectionForField "(Maybe Float)" "carAccelerationSpeed" [] (Decode.float |> Decode.nullable)


{-| When true, realtime updates are ignored during this search.
-}
ignoreRealTimeUpdates : SelectionSet (Maybe Bool) EnturApi.Object.RoutingParameters
ignoreRealTimeUpdates =
    Object.selectionForField "(Maybe Bool)" "ignoreRealTimeUpdates" [] (Decode.bool |> Decode.nullable)


{-| When true, service journeys cancelled in scheduled route data will be included during this search.
-}
includedPlannedCancellations : SelectionSet (Maybe Bool) EnturApi.Object.RoutingParameters
includedPlannedCancellations =
    Object.selectionForField "(Maybe Bool)" "includedPlannedCancellations" [] (Decode.bool |> Decode.nullable)


{-| If true, the remaining weight heuristic is disabled.
-}
disableRemainingWeightHeuristic : SelectionSet (Maybe Bool) EnturApi.Object.RoutingParameters
disableRemainingWeightHeuristic =
    Object.selectionForField "(Maybe Bool)" "disableRemainingWeightHeuristic" [] (Decode.bool |> Decode.nullable)


softWalkLimiting : SelectionSet (Maybe Bool) EnturApi.Object.RoutingParameters
softWalkLimiting =
    Object.selectionForField "(Maybe Bool)" "softWalkLimiting" [] (Decode.bool |> Decode.nullable)


softPreTransitLimiting : SelectionSet (Maybe Bool) EnturApi.Object.RoutingParameters
softPreTransitLimiting =
    Object.selectionForField "(Maybe Bool)" "softPreTransitLimiting" [] (Decode.bool |> Decode.nullable)


{-| A jump in cost when stepping over the walking limit.
-}
softWalkPenalty : SelectionSet (Maybe Float) EnturApi.Object.RoutingParameters
softWalkPenalty =
    Object.selectionForField "(Maybe Float)" "softWalkPenalty" [] (Decode.float |> Decode.nullable)


{-| A jump in cost for every meter over the walking limit.
-}
softWalkOverageRate : SelectionSet (Maybe Float) EnturApi.Object.RoutingParameters
softWalkOverageRate =
    Object.selectionForField "(Maybe Float)" "softWalkOverageRate" [] (Decode.float |> Decode.nullable)


{-| A jump in cost when stepping over the pre-transit time limit.
-}
preTransitPenalty : SelectionSet (Maybe Float) EnturApi.Object.RoutingParameters
preTransitPenalty =
    Object.selectionForField "(Maybe Float)" "preTransitPenalty" [] (Decode.float |> Decode.nullable)


{-| A jump in cost for every second over the pre-transit time limit.
-}
preTransitOverageRate : SelectionSet (Maybe Float) EnturApi.Object.RoutingParameters
preTransitOverageRate =
    Object.selectionForField "(Maybe Float)" "preTransitOverageRate" [] (Decode.float |> Decode.nullable)


{-| -}
allowBikeRental : SelectionSet (Maybe Bool) EnturApi.Object.RoutingParameters
allowBikeRental =
    Object.selectionForField "(Maybe Bool)" "allowBikeRental" [] (Decode.bool |> Decode.nullable)


bikeParkAndRide : SelectionSet (Maybe Bool) EnturApi.Object.RoutingParameters
bikeParkAndRide =
    Object.selectionForField "(Maybe Bool)" "bikeParkAndRide" [] (Decode.bool |> Decode.nullable)


parkAndRide : SelectionSet (Maybe Bool) EnturApi.Object.RoutingParameters
parkAndRide =
    Object.selectionForField "(Maybe Bool)" "parkAndRide" [] (Decode.bool |> Decode.nullable)


kissAndRide : SelectionSet (Maybe Bool) EnturApi.Object.RoutingParameters
kissAndRide =
    Object.selectionForField "(Maybe Bool)" "kissAndRide" [] (Decode.bool |> Decode.nullable)


rideAndKiss : SelectionSet (Maybe Bool) EnturApi.Object.RoutingParameters
rideAndKiss =
    Object.selectionForField "(Maybe Bool)" "rideAndKiss" [] (Decode.bool |> Decode.nullable)


{-| Should traffic congestion be considered when driving?
-}
useTraffic : SelectionSet (Maybe Bool) EnturApi.Object.RoutingParameters
useTraffic =
    Object.selectionForField "(Maybe Bool)" "useTraffic" [] (Decode.bool |> Decode.nullable)


{-| Accept only paths that use transit (no street-only paths).
-}
onlyTransitTrips : SelectionSet (Maybe Bool) EnturApi.Object.RoutingParameters
onlyTransitTrips =
    Object.selectionForField "(Maybe Bool)" "onlyTransitTrips" [] (Decode.bool |> Decode.nullable)


{-| Option to disable the default filtering of GTFS-RT alerts by time.
-}
disableAlertFiltering : SelectionSet (Maybe Bool) EnturApi.Object.RoutingParameters
disableAlertFiltering =
    Object.selectionForField "(Maybe Bool)" "disableAlertFiltering" [] (Decode.bool |> Decode.nullable)


{-| Whether to apply the ellipsoid->geoid offset to all elevations in the response.
-}
geoIdElevation : SelectionSet (Maybe Bool) EnturApi.Object.RoutingParameters
geoIdElevation =
    Object.selectionForField "(Maybe Bool)" "geoIdElevation" [] (Decode.bool |> Decode.nullable)


{-| Whether to apply the ellipsoid->geoid offset to all elevations in the response.
-}
preferredInterchangePenalty : SelectionSet (Maybe Int) EnturApi.Object.RoutingParameters
preferredInterchangePenalty =
    Object.selectionForField "(Maybe Int)" "preferredInterchangePenalty" [] (Decode.int |> Decode.nullable)


{-| Whether to apply the ellipsoid->geoid offset to all elevations in the response.
-}
recommendedInterchangePenalty : SelectionSet (Maybe Int) EnturApi.Object.RoutingParameters
recommendedInterchangePenalty =
    Object.selectionForField "(Maybe Int)" "recommendedInterchangePenalty" [] (Decode.int |> Decode.nullable)


{-| Whether to apply the ellipsoid->geoid offset to all elevations in the response.
-}
interchangeAllowedPenalty : SelectionSet (Maybe Int) EnturApi.Object.RoutingParameters
interchangeAllowedPenalty =
    Object.selectionForField "(Maybe Int)" "interchangeAllowedPenalty" [] (Decode.int |> Decode.nullable)


{-| Whether to apply the ellipsoid->geoid offset to all elevations in the response.
-}
noInterchangePenalty : SelectionSet (Maybe Int) EnturApi.Object.RoutingParameters
noInterchangePenalty =
    Object.selectionForField "(Maybe Int)" "noInterchangePenalty" [] (Decode.int |> Decode.nullable)


{-| How much worse driving before and after transit is than riding on transit. Applies to ride and kiss, kiss and ride and park and ride.
-}
preTransitReluctance : SelectionSet (Maybe Float) EnturApi.Object.RoutingParameters
preTransitReluctance =
    Object.selectionForField "(Maybe Float)" "preTransitReluctance" [] (Decode.float |> Decode.nullable)
