-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.TariffZone exposing (id, name)

import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.ScalarCodecs
import EnturApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet (Maybe String) EnturApi.Object.TariffZone
id =
    Object.selectionForField "(Maybe String)" "id" [] (Decode.string |> Decode.nullable)


name : SelectionSet (Maybe String) EnturApi.Object.TariffZone
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)
