-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.TimetabledPassingTime exposing (..)

import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.ScalarCodecs
import EnturApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


quay : SelectionSet decodesTo EnturApi.Object.Quay -> SelectionSet (Maybe decodesTo) EnturApi.Object.TimetabledPassingTime
quay object_ =
    Object.selectionForCompositeField "quay" [] object_ (identity >> Decode.nullable)


{-| Scheduled time of arrival at quay
-}
arrival : SelectionSet decodesTo EnturApi.Object.TimeAndDayOffset -> SelectionSet (Maybe decodesTo) EnturApi.Object.TimetabledPassingTime
arrival object_ =
    Object.selectionForCompositeField "arrival" [] object_ (identity >> Decode.nullable)


{-| Scheduled time of departure from quay
-}
departure : SelectionSet decodesTo EnturApi.Object.TimeAndDayOffset -> SelectionSet (Maybe decodesTo) EnturApi.Object.TimetabledPassingTime
departure object_ =
    Object.selectionForCompositeField "departure" [] object_ (identity >> Decode.nullable)


{-| Whether this is a timing point or not. Boarding and alighting is not allowed at timing points.
-}
timingPoint : SelectionSet (Maybe Bool) EnturApi.Object.TimetabledPassingTime
timingPoint =
    Object.selectionForField "(Maybe Bool)" "timingPoint" [] (Decode.bool |> Decode.nullable)


{-| Whether vehicle may be boarded at quay.
-}
forBoarding : SelectionSet (Maybe Bool) EnturApi.Object.TimetabledPassingTime
forBoarding =
    Object.selectionForField "(Maybe Bool)" "forBoarding" [] (Decode.bool |> Decode.nullable)


{-| Whether vehicle may be alighted at quay.
-}
forAlighting : SelectionSet (Maybe Bool) EnturApi.Object.TimetabledPassingTime
forAlighting =
    Object.selectionForField "(Maybe Bool)" "forAlighting" [] (Decode.bool |> Decode.nullable)


{-| Whether vehicle will only stop on request.
-}
requestStop : SelectionSet (Maybe Bool) EnturApi.Object.TimetabledPassingTime
requestStop =
    Object.selectionForField "(Maybe Bool)" "requestStop" [] (Decode.bool |> Decode.nullable)


serviceJourney : SelectionSet decodesTo EnturApi.Object.ServiceJourney -> SelectionSet (Maybe decodesTo) EnturApi.Object.TimetabledPassingTime
serviceJourney object_ =
    Object.selectionForCompositeField "serviceJourney" [] object_ (identity >> Decode.nullable)


destinationDisplay : SelectionSet decodesTo EnturApi.Object.DestinationDisplay -> SelectionSet (Maybe decodesTo) EnturApi.Object.TimetabledPassingTime
destinationDisplay object_ =
    Object.selectionForCompositeField "destinationDisplay" [] object_ (identity >> Decode.nullable)


notices : SelectionSet decodesTo EnturApi.Object.Notice -> SelectionSet (List (Maybe decodesTo)) EnturApi.Object.TimetabledPassingTime
notices object_ =
    Object.selectionForCompositeField "notices" [] object_ (identity >> Decode.nullable >> Decode.list)


{-| Booking arrangements for flexible service.
-}
bookingArrangements : SelectionSet decodesTo EnturApi.Object.BookingArrangement -> SelectionSet (Maybe decodesTo) EnturApi.Object.TimetabledPassingTime
bookingArrangements object_ =
    Object.selectionForCompositeField "bookingArrangements" [] object_ (identity >> Decode.nullable)
