-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.TimeAndDayOffset exposing (..)

import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.ScalarCodecs
import EnturApi.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Local time
-}
time : SelectionSet (Maybe EnturApi.ScalarCodecs.Time) EnturApi.Object.TimeAndDayOffset
time =
    Object.selectionForField "(Maybe ScalarCodecs.Time)" "time" [] (EnturApi.ScalarCodecs.codecs |> EnturApi.Scalar.unwrapCodecs |> .codecTime |> .decoder |> Decode.nullable)


{-| Number of days offset from base line time
-}
dayOffset : SelectionSet (Maybe Int) EnturApi.Object.TimeAndDayOffset
dayOffset =
    Object.selectionForField "(Maybe Int)" "dayOffset" [] (Decode.int |> Decode.nullable)
