-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Enum.Locale exposing (Locale(..), decoder, fromString, list, toString)

import Json.Decode as Decode exposing (Decoder)


type Locale
    = No
    | Us


list : List Locale
list =
    [ No, Us ]


decoder : Decoder Locale
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "no" ->
                        Decode.succeed No

                    "us" ->
                        Decode.succeed Us

                    _ ->
                        Decode.fail ("Invalid Locale type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Locale -> String
toString enum =
    case enum of
        No ->
            "no"

        Us ->
            "us"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Locale
fromString enumString =
    case enumString of
        "no" ->
            Just No

        "us" ->
            Just Us

        _ ->
            Nothing
