-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Enum.PurchaseMoment exposing (..)

import Json.Decode as Decode exposing (Decoder)


type PurchaseMoment
    = OnReservation
    | BeforeBoarding
    | OnBoarding
    | AfterBoarding
    | OnCheckOut
    | Other


list : List PurchaseMoment
list =
    [ OnReservation, BeforeBoarding, OnBoarding, AfterBoarding, OnCheckOut, Other ]


decoder : Decoder PurchaseMoment
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "onReservation" ->
                        Decode.succeed OnReservation

                    "beforeBoarding" ->
                        Decode.succeed BeforeBoarding

                    "onBoarding" ->
                        Decode.succeed OnBoarding

                    "afterBoarding" ->
                        Decode.succeed AfterBoarding

                    "onCheckOut" ->
                        Decode.succeed OnCheckOut

                    "other" ->
                        Decode.succeed Other

                    _ ->
                        Decode.fail ("Invalid PurchaseMoment type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : PurchaseMoment -> String
toString enum =
    case enum of
        OnReservation ->
            "onReservation"

        BeforeBoarding ->
            "beforeBoarding"

        OnBoarding ->
            "onBoarding"

        AfterBoarding ->
            "afterBoarding"

        OnCheckOut ->
            "onCheckOut"

        Other ->
            "other"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe PurchaseMoment
fromString enumString =
    case enumString of
        "onReservation" ->
            Just OnReservation

        "beforeBoarding" ->
            Just BeforeBoarding

        "onBoarding" ->
            Just OnBoarding

        "afterBoarding" ->
            Just AfterBoarding

        "onCheckOut" ->
            Just OnCheckOut

        "other" ->
            Just Other

        _ ->
            Nothing
