-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Enum.ServiceAlteration exposing (..)

import Json.Decode as Decode exposing (Decoder)


type ServiceAlteration
    = Planned
    | Cancellation
    | ExtraJourney
    | Replaced


list : List ServiceAlteration
list =
    [ Planned, Cancellation, ExtraJourney, Replaced ]


decoder : Decoder ServiceAlteration
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "planned" ->
                        Decode.succeed Planned

                    "cancellation" ->
                        Decode.succeed Cancellation

                    "extraJourney" ->
                        Decode.succeed ExtraJourney

                    "replaced" ->
                        Decode.succeed Replaced

                    _ ->
                        Decode.fail ("Invalid ServiceAlteration type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : ServiceAlteration -> String
toString enum =
    case enum of
        Planned ->
            "planned"

        Cancellation ->
            "cancellation"

        ExtraJourney ->
            "extraJourney"

        Replaced ->
            "replaced"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe ServiceAlteration
fromString enumString =
    case enumString of
        "planned" ->
            Just Planned

        "cancellation" ->
            Just Cancellation

        "extraJourney" ->
            Just ExtraJourney

        "replaced" ->
            Just Replaced

        _ ->
            Nothing
