-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object exposing (..)


type Authority
    = Authority


type BikePark
    = BikePark


type BikeRentalStation
    = BikeRentalStation


type BookingArrangement
    = BookingArrangement


type Branding
    = Branding


type CarPark
    = CarPark


type Contact
    = Contact


type DebugOutput
    = DebugOutput


type DestinationDisplay
    = DestinationDisplay


type EstimatedCall
    = EstimatedCall


type InfoLink
    = InfoLink


type Interchange
    = Interchange


type JourneyPattern
    = JourneyPattern


type KeyValue
    = KeyValue


type Leg
    = Leg


type Line
    = Line


type MultilingualString
    = MultilingualString


type Notice
    = Notice


type Operator
    = Operator


type Organisation
    = Organisation


type PageInfo
    = PageInfo


type PathGuidance
    = PathGuidance


type Place
    = Place


type PlaceAtDistance
    = PlaceAtDistance


type PlaceAtDistanceConnection
    = PlaceAtDistanceConnection


type PlaceAtDistanceEdge
    = PlaceAtDistanceEdge


type PointsOnLink
    = PointsOnLink


type Presentation
    = Presentation


type PtSituationElement
    = PtSituationElement


type Quay
    = Quay


type QuayAtDistance
    = QuayAtDistance


type QuayAtDistanceConnection
    = QuayAtDistanceConnection


type QuayAtDistanceEdge
    = QuayAtDistanceEdge


type RoutingParameters
    = RoutingParameters


type ServiceJourney
    = ServiceJourney


type StopPlace
    = StopPlace


type TariffZone
    = TariffZone


type TimeAndDayOffset
    = TimeAndDayOffset


type TimetabledPassingTime
    = TimetabledPassingTime


type Trip
    = Trip


type TripPattern
    = TripPattern


type ValidityPeriod
    = ValidityPeriod
